// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateDeclaracionData, CreateDeclaracionErrors, CreateDeclaracionResponses, GetDeclaracionData, GetDeclaracionErrors, GetDeclaracionResponses, GetPreguntasData, GetPreguntasErrors, GetPreguntasResponses, ListDeclaracionesData, ListDeclaracionesErrors, ListDeclaracionesResponses, UpdateEstadoDeclaracionData, UpdateEstadoDeclaracionErrors, UpdateEstadoDeclaracionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Obtiene el catálogo de preguntas
 *
 * Devuelve todas las secciones del cuestionario con sus preguntas
 * ordenadas, incluyendo condiciones de visibilidad condicional.
 *
 */
export const getPreguntas = <ThrowOnError extends boolean = false>(options?: Options<GetPreguntasData, ThrowOnError>) => (options?.client ?? client).get<GetPreguntasResponses, GetPreguntasErrors, ThrowOnError>({ url: '/irpf/preguntas', ...options });

/**
 * Lista las declaraciones registradas
 *
 * Devuelve una lista paginada de declaraciones (uso interno/administración).
 */
export const listDeclaraciones = <ThrowOnError extends boolean = false>(options?: Options<ListDeclaracionesData, ThrowOnError>) => (options?.client ?? client).get<ListDeclaracionesResponses, ListDeclaracionesErrors, ThrowOnError>({ url: '/irpf/declaraciones', ...options });

/**
 * Envía un cuestionario fiscal completo
 *
 * Recibe el cuestionario IRPF relleno junto con la documentación
 * adjunta en formato `multipart/form-data`. Crea una nueva declaración
 * en estado `recibido`.
 *
 */
export const createDeclaracion = <ThrowOnError extends boolean = false>(options: Options<CreateDeclaracionData, ThrowOnError>) => (options.client ?? client).post<CreateDeclaracionResponses, CreateDeclaracionErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/irpf/declaraciones',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Obtiene el detalle de una declaración
 */
export const getDeclaracion = <ThrowOnError extends boolean = false>(options: Options<GetDeclaracionData, ThrowOnError>) => (options.client ?? client).get<GetDeclaracionResponses, GetDeclaracionErrors, ThrowOnError>({ url: '/irpf/declaraciones/{id}', ...options });

/**
 * Actualiza el estado de una declaración
 */
export const updateEstadoDeclaracion = <ThrowOnError extends boolean = false>(options: Options<UpdateEstadoDeclaracionData, ThrowOnError>) => (options.client ?? client).patch<UpdateEstadoDeclaracionResponses, UpdateEstadoDeclaracionErrors, ThrowOnError>({
    url: '/irpf/declaraciones/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
