// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.renta-form.example/v1' | 'http://localhost:3001/v1' | (string & {});
};

/**
 * Respuesta de tipo Sí/No
 */
export type RespuestaYn = 'si' | 'no';

export type EstadoExpediente = 'recibido' | 'en_revision' | 'documentacion_pendiente' | 'completado' | 'archivado';

export type TipoDocumento = 'dni_anverso' | 'dni_reverso' | 'adicional';

export type Pregunta = {
    /**
     * Identificador único (coincide con el nombre del campo en el formulario)
     */
    id: string;
    /**
     * Texto de la pregunta que se muestra al usuario
     */
    texto: string;
};

export type Seccion = {
    id: string;
    numero: number;
    titulo: string;
    preguntas: Array<Pregunta>;
};

export type CatalogoPreguntas = {
    secciones: Array<Seccion>;
};

export type DeclaracionInput = {
    nombre: string;
    apellidos: string;
    dniNie: string;
    email: string;
    telefono: string;
    viviendaAlquiler: RespuestaYn;
    alquilerMenos35?: RespuestaYn;
    viviendaPropiedad: RespuestaYn;
    propiedadAntes2013?: RespuestaYn;
    pisosAlquiladosTerceros: RespuestaYn;
    segundaResidencia: RespuestaYn;
    familiaNumerosa: RespuestaYn;
    ayudasGobierno: RespuestaYn;
    mayores65ACargo: RespuestaYn;
    mayoresConviven?: RespuestaYn;
    hijosMenores26: RespuestaYn;
    ingresosJuego: RespuestaYn;
    ingresosInversiones: RespuestaYn;
    /**
     * Anverso del DNI/NIE (PDF, JPG, PNG; máx. 5 MB)
     */
    docDniAnverso?: Blob | File;
    /**
     * Reverso del DNI/NIE (PDF, JPG, PNG; máx. 5 MB)
     */
    docDniReverso?: Blob | File;
    /**
     * Documentación adicional (nóminas, certificados, etc.)
     */
    docAdicional?: Array<Blob | File>;
    /**
     * Situaciones especiales a tener en cuenta
     */
    comentarios?: string;
};

export type DeclaracionCreada = {
    id: string;
    estado: EstadoExpediente;
    creadoEn: string;
};

export type Documento = {
    id: string;
    tipo: TipoDocumento;
    nombreOriginal: string;
    mimeType: string;
    /**
     * Tamaño en bytes
     */
    tamanyo: number;
    /**
     * URL de acceso al documento (si se almacena externamente)
     */
    url?: string;
    subidoEn: string;
};

export type Declaracion = DeclaracionCreada & {
    nombre: string;
    apellidos: string;
    dniNie: string;
    email: string;
    telefono: string;
    viviendaAlquiler: RespuestaYn;
    alquilerMenos35?: RespuestaYn;
    viviendaPropiedad: RespuestaYn;
    propiedadAntes2013?: RespuestaYn;
    pisosAlquiladosTerceros: RespuestaYn;
    segundaResidencia: RespuestaYn;
    familiaNumerosa: RespuestaYn;
    ayudasGobierno: RespuestaYn;
    mayores65ACargo: RespuestaYn;
    mayoresConviven?: RespuestaYn;
    hijosMenores26: RespuestaYn;
    ingresosJuego: RespuestaYn;
    ingresosInversiones: RespuestaYn;
    comentarios?: string;
    actualizadoEn: string;
    documentos: Array<Documento>;
};

export type ListaDeclaraciones = {
    data: Array<Declaracion>;
    total: number;
    page: number;
    limit: number;
};

export type Error = {
    code: string;
    message: string;
};

export type ErrorValidacion = Error & {
    errores?: Array<{
        campo: string;
        mensaje: string;
    }>;
};

/**
 * UUID de la declaración
 */
export type IdParam = string;

export type PageParam = number;

export type LimitParam = number;

export type GetPreguntasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/irpf/preguntas';
};

export type GetPreguntasErrors = {
    /**
     * Servicio no disponible
     */
    503: Error;
};

export type GetPreguntasError = GetPreguntasErrors[keyof GetPreguntasErrors];

export type GetPreguntasResponses = {
    /**
     * Catálogo de preguntas obtenido correctamente
     */
    200: CatalogoPreguntas;
};

export type GetPreguntasResponse = GetPreguntasResponses[keyof GetPreguntasResponses];

export type ListDeclaracionesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Filtra por estado del expediente
         */
        estado?: EstadoExpediente;
        /**
         * Filtra por DNI/NIE del contribuyente
         */
        dniNie?: string;
    };
    url: '/irpf/declaraciones';
};

export type ListDeclaracionesErrors = {
    /**
     * No autorizado
     */
    401: Error;
};

export type ListDeclaracionesError = ListDeclaracionesErrors[keyof ListDeclaracionesErrors];

export type ListDeclaracionesResponses = {
    /**
     * Lista de declaraciones
     */
    200: ListaDeclaraciones;
};

export type ListDeclaracionesResponse = ListDeclaracionesResponses[keyof ListDeclaracionesResponses];

export type CreateDeclaracionData = {
    body: DeclaracionInput;
    path?: never;
    query?: never;
    url: '/irpf/declaraciones';
};

export type CreateDeclaracionErrors = {
    /**
     * Datos de entrada inválidos
     */
    400: ErrorValidacion;
    /**
     * Entidad no procesable (restricciones de negocio)
     */
    422: Error;
    /**
     * Servicio no disponible
     */
    503: Error;
};

export type CreateDeclaracionError = CreateDeclaracionErrors[keyof CreateDeclaracionErrors];

export type CreateDeclaracionResponses = {
    /**
     * Declaración creada correctamente
     */
    201: DeclaracionCreada;
};

export type CreateDeclaracionResponse = CreateDeclaracionResponses[keyof CreateDeclaracionResponses];

export type GetDeclaracionData = {
    body?: never;
    path: {
        /**
         * UUID de la declaración
         */
        id: string;
    };
    query?: never;
    url: '/irpf/declaraciones/{id}';
};

export type GetDeclaracionErrors = {
    /**
     * Declaración no encontrada
     */
    404: Error;
};

export type GetDeclaracionError = GetDeclaracionErrors[keyof GetDeclaracionErrors];

export type GetDeclaracionResponses = {
    /**
     * Detalle de la declaración
     */
    200: Declaracion;
};

export type GetDeclaracionResponse = GetDeclaracionResponses[keyof GetDeclaracionResponses];

export type UpdateEstadoDeclaracionData = {
    body: {
        estado: EstadoExpediente;
    };
    path: {
        /**
         * UUID de la declaración
         */
        id: string;
    };
    query?: never;
    url: '/irpf/declaraciones/{id}';
};

export type UpdateEstadoDeclaracionErrors = {
    /**
     * Declaración no encontrada
     */
    404: Error;
};

export type UpdateEstadoDeclaracionError = UpdateEstadoDeclaracionErrors[keyof UpdateEstadoDeclaracionErrors];

export type UpdateEstadoDeclaracionResponses = {
    /**
     * Estado actualizado correctamente
     */
    200: Declaracion;
};

export type UpdateEstadoDeclaracionResponse = UpdateEstadoDeclaracionResponses[keyof UpdateEstadoDeclaracionResponses];
